#!/usr/bin/env python3
"""
kconfig_gen.py — Kconfig configurator for AHRS

Usage:
    kconfig_gen.py defconfig --board <BOARD>     生成默认 .config
    kconfig_gen.py gen --board <BOARD>            生成 auto_config.h
    kconfig_gen.py menuconfig --board <BOARD>     交互式配置
"""

import sys
import os
import argparse

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def resolve_paths(board):
    board_dir  = os.path.join(PROJECT_ROOT, "board", board)
    build_dir  = os.path.join(PROJECT_ROOT, "build", board)
    kconfig    = os.path.join(PROJECT_ROOT, "Kconfig")
    dotconfig  = os.path.join(board_dir, ".config")
    autoconf   = os.path.join(build_dir, "generated", "kconfig_gen.h")
    return kconfig, dotconfig, autoconf, build_dir


def _load(kconfig, dotconfig):
    try:
        import kconfiglib
    except ImportError:
        print("Error: kconfiglib not installed. Run: pip install kconfiglib")
        sys.exit(1)

    kconf = kconfiglib.Kconfig(kconfig)
    if os.path.exists(dotconfig):
        kconf.load_config(dotconfig)
    return kconf, kconfiglib


def cmd_defconfig(kconfig, dotconfig, _autoconf, build_dir):
    os.makedirs(build_dir, exist_ok=True)
    kconf, _ = _load(kconfig, dotconfig)
    kconf.write_config(dotconfig)
    print(f"  GEN     {dotconfig}")


def cmd_gen(kconfig, dotconfig, autoconf, build_dir):
    os.makedirs(os.path.dirname(autoconf), exist_ok=True)
    kconf, kconfiglib = _load(kconfig, dotconfig)

    with open(autoconf, "w") as f:
        f.write("/* Generated by kconfig_gen.py — DO NOT EDIT */\n")
        f.write("#ifndef __KCONFIG_GEN_H__\n")
        f.write("#define __KCONFIG_GEN_H__\n\n")

        for sym in kconf.unique_defined_syms:
            name = sym.name
            val  = sym.str_value
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                f.write(f"#define CONFIG_{name}  {1 if val == 'y' else 0}\n")
            elif sym.type in (kconfiglib.INT, kconfiglib.HEX):
                f.write(f"#define CONFIG_{name}  {val}\n")
            elif sym.type == kconfiglib.STRING:
                f.write(f'#define CONFIG_{name}  "{val}"\n')

        f.write("\n#endif /* __KCONFIG_GEN_H__ */\n")
    print(f"  GEN     {autoconf}")


def cmd_menuconfig(kconfig, dotconfig, autoconf, build_dir):
    import menuconfig
    os.makedirs(os.path.dirname(autoconf), exist_ok=True)
    kconf, _ = _load(kconfig, dotconfig)
    kconf.warn = False
    menuconfig.menuconfig(kconf)
    kconf.write_config(dotconfig)
    print(f"  SAVED   {dotconfig}")
    cmd_gen(kconfig, dotconfig, autoconf, build_dir)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["defconfig", "gen", "menuconfig"])
    parser.add_argument("--board", required=True, help="Board path, e.g. stm32/g4/stm32g431kbu6/v1")
    args = parser.parse_args()

    kconfig, dotconfig, autoconf, build_dir = resolve_paths(args.board)

    if not os.path.exists(kconfig):
        print(f"Error: Kconfig not found: {kconfig}")
        sys.exit(1)

    os.chdir(PROJECT_ROOT)

    if args.command == "defconfig":
        cmd_defconfig(kconfig, dotconfig, autoconf, build_dir)
    elif args.command == "gen":
        cmd_gen(kconfig, dotconfig, autoconf, build_dir)
    elif args.command == "menuconfig":
        cmd_menuconfig(kconfig, dotconfig, autoconf, build_dir)


if __name__ == "__main__":
    main()
